language: python
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
sudo: false

# TODO: start mongodb once more complex tests are implemented
# services: mongodb

install: pip install -U tox
script: tox -v
